  api:
    build: ./api
    command: sh -c "npm run migrate && npm run && npm run start"
    container_name: challenge-doctor-api
    env_file:
      - ./.env
    ports:
      - 3001:3001
    volumes:
      - ./api:/home/app/api
      - /home/app/api/node_modules
    working_dir: /home/app/api
    restart: on-failure
    depends_on:
      - db
      - db-test
  db:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
  db-test:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5430:5432